### ISSUE TITLE
Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`

### ISSUE THREAD

**Issue by PabloSzx** [jagaapple/next-secure-headers#11]
Hi, when using this module you get this message

```
Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`.
Read more: https://err.sh/next.js/opt-out-auto-static-optimization
```

Is it possible to use modify this module so this doesn't happen?

**Comment by jagaapple** [comment]
@PabloSzx 
This package needs to access a request object and we can access it in only `getInitialProps` lifecycle provided by Next.js, so unfortunately it's impossible 😢
If you are creating a static website using Next.js, you have to configure some headers in Express.js layer instead, such as [Helmet](https://github.com/helmetjs/helmet).
