### ISSUE TITLE
Typo in README file, `soruce` instead of `source`

### ISSUE THREAD

**Issue by omieliekh** [jagaapple/next-secure-headers#26]
# 💩 Bug Report
## A summary of the bug
Hello, 
There is a typo in README file in property name. It says `soruce`, but it should be `source` instead.
There are 4 places in a file with this typo, to be precise.

## Environment
- This project version(s): `v2.0.0`

---

- [x] I've tried to find similar issues
- [x] I would like to work on a fix 💪🏻

**Comment by jagaapple** [comment]
Oops.
Thank you, I'll fix it later.
