### ISSUE TITLE
Minor typo in root readme

### ISSUE THREAD

**Issue by nk1tz** [jagaapple/next-secure-headers#28]
In multiple examples:
`soruce` vs `source`

<img width="206" alt="Screen Shot 2020-08-25 at 1 07 17 PM" src="https://user-images.githubusercontent.com/12980165/91222421-ff10cb00-e6d3-11ea-90ba-f0431c52f4f7.png">

**Comment by jagaapple** [comment]
Closing as duplicate of #26
