### ISSUE TITLE
Support spec names of CSP directives

### ISSUE THREAD

**Issue by dbo** [jagaapple/next-secure-headers#30]
# 🌱 Feature Request
## Is your feature request related to a problem? Please describe.
The spec defines directives in kebab-case, e.g. `script-src`, these are currently not picked up, but appear as `undefined`.

## Describe the solution you'd like
Since the camel-cased directives are sensible as well, supporting both would be nice.

**Comment by jagaapple** [comment]
This has been supported in 2.1.0. Thank you.
